## 2.1 넘파이 소개

In [1]:
!pip install numpy

In [2]:
import numpy as np 

data = [1, 2, 3]
arr = np.array(data)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
data = [1, 2, 3]

result = []
for i in data:
    result.append(i * 10)

print(result)

[10, 20, 30]


In [5]:
import numpy as np

arr = np.array([1, 2, 3])
result = arr * 10
print(result)

[10 20 30]


In [8]:
data2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(data2d[0])

[1, 2, 3]


In [7]:
import numpy as np

arr = np.array(data2d)
print(arr[:, 0])

[1 4 7]


## 2.2 ndarray

In [9]:
data1 = [1, 2, 3, 4]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
data2 = [
    [1, 2],
    [3, 4]
]
arr2 = np.array(data2)

print(arr2)
print(type(arr2))
print(type(arr2[0]))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

(2, 2)
2
int64


In [14]:
print(arr1.shape)

(4,)


In [15]:
arr1

array([1, 2, 3, 4])

In [18]:
data = [
    [1],
    [2],
    [3],
    [4]
]

c = np.array(data)
print(c.shape)

(4, 1)


In [19]:
print(np.zeros(3))
print(np.ones(3))

[0. 0. 0.]
[1. 1. 1.]


In [20]:
size = (3, 4)
print(np.zeros(size))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
print(np.zeros((3, 4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
print(np.arange(5))
print(np.arange(1, 5))
print(np.arange(1, 5, 2))

[0 1 2 3 4]
[1 2 3 4]
[1 3]


## 2.3 데이터 타입

In [26]:
arr = np.array([1, 2, 3], dtype=np.uint8)
print(arr.dtype)
print(arr.dtype.kind)
print(arr.dtype.alignment)

uint8
u
1


In [27]:
arr = arr.astype('int8')
print(arr.dtype)

int8


In [28]:
a = np.array([0, 255], dtype=np.uint8)
b = a.astype('int8')
print(a)
print(b)

[  0 255]
[ 0 -1]


In [29]:
a16 = np.array([1.333333], dtype=np.float16)
a32 = np.array([1.333333], dtype=np.float32)
print(a16)
print(a32)

[1.333]
[1.333333]


In [34]:
a16 = np.array([1.0], dtype=np.float16)
a32 = np.array([1.0], dtype=np.float32)
print(a16/3)
print(a32/3)

[0.3333]
[0.33333334]


In [37]:
print(np.nan, type(np.nan))
print(np.inf, type(np.inf))
print(-np.inf, type(-np.inf))

nan <class 'float'>
inf <class 'float'>
-inf <class 'float'>


In [38]:
arr = np.array([-1, 2, -3])
print(arr/0)

[-inf  inf -inf]


<ipython-input-38-cb6c03859f6d>:2: RuntimeWarning: divide by zero encountered in true_divide
  print(arr/0)


In [39]:
arr = np.array([-1, 2, -3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


## 2.4 인덱싱과 슬라이싱

In [40]:
arr = np.arange(4)
print(arr[0])

0


In [41]:
arr = np.arange(4).reshape(2, 2)
print(arr[0])

[0 1]


In [42]:
print(arr[0][0])

0


In [43]:
print(arr[0][0])
print(arr[0, 0])

0
0


In [44]:
a = np.arange(10000).reshape(100, 100)
%timeit a[0, 50]

88.4 ns ± 0.483 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [45]:
a = np.arange(10000).reshape(100, 100)
%timeit a[0][50]

155 ns ± 0.455 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [46]:
arr = np.arange(4)
print(arr[:2])

[0 1]


In [47]:
target = [0, 2]
print(arr[target])

[0 2]


In [48]:
print(arr[ [0, 2] ])

[0 2]


In [51]:
arr = np.arange(20).reshape(4, 5)
print(arr[:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [52]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
result = []
for row in arr:
    row_01 = [row[0], row[1]]
    result.append(row_01)

print(result)

[[0, 1], [5, 6], [10, 11], [15, 16]]


In [54]:
print(arr[:, :2])

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]


In [55]:
print(arr[1:4, 2:5])
print(arr[1:, 2:])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


## 브로드캐스팅

In [56]:
a = np.array( [1, 2, 3] )
b = np.array( [2, 3, 4] )
print(a + b)
print(a * b)
print(a % b)

[3 5 7]
[ 2  6 12]
[1 2 3]


In [57]:
print(a + 3)

[4 5 6]


In [58]:
high = [92700, 92400, 92100, 94300, 92300]
low = [90000, 91100, 91700, 92100, 90900]

arr_high = np.array(high)
arr_low = np.array(low)

arr_diff = arr_high - arr_low
print(arr_diff)

[2700 1300  400 2200 1400]


In [60]:
arr_high_x3 = arr_high * 3
arr_low_x2 = arr_low * 2
print(arr_high_x3 + arr_low_x2)

[458100 459400 459700 467100 458700]


In [61]:
avg = (arr_high * 3) + arr_low * 2

In [62]:
data = [
    [92700, 92400, 92100, 94300, 92300],
    [90000, 91100, 91700, 92100, 90900]
]
arr = np.array(data)

In [63]:
print(arr[0] * 3 + arr[1]  * 2)

[458100 459400 459700 467100 458700]


In [64]:
weight = np.array([3, 2]).reshape(2, 1)

In [66]:
print((weight * arr).sum(axis=0))

[458100 459400 459700 467100 458700]


## 2.6 조건 연산

In [67]:
arr = np.array( [10, 20, 30] )
print(arr > 10)

[False  True  True]


In [68]:
arr = np.array([10, 20, 30])
cond = [False, True, True]
print(arr[ cond ])

[20 30]


In [69]:
arr = np.array([10, 20, 30])
print(arr[[False, True, True] ])

[20 30]


In [70]:
arr = np.array([10, 20, 30])
cond = arr > 10
print(arr[ cond ])

[20 30]


In [71]:
print(arr[ arr > 10 ])

[20 30]


In [72]:
cond.all()

False

In [73]:
cond.any()

True

In [74]:
arr = np.array([10, 20, 30])
cond0 = arr > 10
cond1 = arr < 30
print(arr[ cond0 & cond1 ])

[20]


In [75]:
arr = np.array([10, 20, 30])
print(arr[ (arr > 10) & (arr < 30) ])

[20]


In [76]:
arr = np.array([10, 20, 30])
cond = arr > 10
arr[cond] = 1
arr[~cond] = 0
print(arr)

[0 1 1]


In [77]:
arr = np.array([10, 20, 30])
arr = np.where( arr > 10, 1, 0)
print(arr)

[0 1 1]


In [79]:
cond = arr > 10
arr[cond] = arr[cond] + 10
arr[~cond] = arr[~cond] - 10

In [80]:
arr

array([-10,  -9,  -9])

In [82]:
arr = np.array([10, 20, 30])
arr = np.where( arr > 10, arr+10, arr-10)
print(arr)

[ 0 30 40]


In [83]:
lge = np.array([93000, 82400, 99100, 81000, 72300])
result = lge[  lge <= 85000  ]
print( len(result) )

3


## 함수와 메서드

In [84]:
arr = np.arange(8).reshape(4, 2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [85]:
print(arr.sum())

28


In [86]:
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[12 16]
[ 1  5  9 13]


In [87]:
np.random.randint(3)

0

In [88]:
np.random.randint(46, size=5)

array([14, 13, 18,  3, 25])

In [90]:
np.random.randint(46, size=(2, 5))

array([[ 6,  6, 43, 22, 10],
       [34, 25,  2, 32, 21]])

In [91]:
x = np.linspace(0, 10, 3)
print(x)

[ 0.  5. 10.]


In [92]:
y = x ** 2

In [93]:
y

array([  0.,  25., 100.])

In [94]:
a = np.arange(4)
b = np.arange(4, 8)
c = np.vstack([a, b])
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [95]:
np.hstack([a, b])

array([0, 1, 2, 3, 4, 5, 6, 7])