## 6.1 일차원 ndarray와 view

In [124]:
import numpy as np

a = np.array([ 10, 20, 30 ])
b = a[ 1: ]

In [125]:
print(a.__array_interface__)

{'data': (2500800231264, False), 'strides': None, 'descr': [('', '<i4')], 'typestr': '<i4', 'shape': (3,), 'version': 3}


In [128]:
print(a.strides)

(4,)


In [4]:
print(b.__array_interface__)

{'data': (2614827516676, False), 'strides': None, 'descr': [('', '<i4')], 'typestr': '<i4', 'shape': (2,), 'version': 3}


In [5]:
a.strides

(4,)

In [6]:
print(a.__array_interface__['data'][0])
print(b.__array_interface__['data'][0])

2614827516672
2614827516676


In [7]:
b[0] = 200
print( a )
print( b )

[ 10 200  30]
[200  30]


In [8]:
a = np.array( [ 10, 20, 30 ] )
b = a[ [0, 2] ]
print(a.__array_interface__['data'][0])
print(b.__array_interface__['data'][0])

2614827513952
2614828403904


In [9]:
a = np.array( [ 10, 20, 30 ] )
b = a[ a >= 20 ]
print(a.__array_interface__['data'][0])
print(b.__array_interface__['data'][0])

2614827516672
2614829261856


In [10]:
b = a.view()
c = a.copy()

In [11]:
b = a.view(dtype=np.int16)
c = a.astype(dtype=np.int16)

In [12]:
print(b.__array_interface__['data'][0])
print(c.__array_interface__['data'][0])

2614827516672
2614829261488


In [5]:
a = np.array( [ 10, 20, 30 ] )
b = a[  1 : ]
print(a.base)
print(a.flags.owndata)
print(b.base)
print(b.flags.owndata)

None
True
[10 20 30]
False


In [ ]:
np.shares_memory(a, b)

## 6.2 이차원 ndarray와 view

In [98]:
import numpy as np

a = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
])
print(a.__array_interface__)
print(a.strides)

{'data': (2500822179248, False), 'strides': None, 'descr': [('', '<i4')], 'typestr': '<i4', 'shape': (3, 3), 'version': 3}
(12, 4)


In [102]:
%timeit a[0]

107 ns ± 0.542 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [103]:
%timeit a[:, 0]

161 ns ± 0.604 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [104]:
%timeit a[0] + a[1]

512 ns ± 7.86 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [105]:
%timeit a[:, 0] + a[:, 1]

1 µs ± 3.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
])
b = a[ :2, :2 ]
print(a.__array_interface__['data'][0])
print(b.__array_interface__['data'][0])

2614824950160
2614824950160


In [16]:
b = a[ 1:3, [0, 2] ]
print(b.__array_interface__['data'][0])

2614827514208


In [17]:
b = a[ [True, False, True],  :2 ]
print(b.__array_interface__['data'][0])

2614827513984


## 6.3 판다스와 view

In [106]:
from pandas import DataFrame 

data = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
]
index = ["a", "b", "c"]
columns = ["x", "y", "z"]

df = DataFrame( data, index, columns)
print(df.values.__array_interface__)

{'data': (2500818924384, False), 'strides': (8, 24), 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (3, 3), 'version': 3}


In [3]:
print(df.values.__array_interface__['data'][0])
print(df.iloc[1].values.__array_interface__['data'][0])
print(df.iloc[2].values.__array_interface__['data'][0])
print(df['y'].values.__array_interface__['data'][0])

2296116878752
2296116878760
2296116878768
2296116878776


In [107]:
import numpy as np

data = np.arange(9).reshape(3, 3)
index = ["a", "b", "c"]
columns = ["x", "y", "z"]

df = DataFrame( data, index, columns)
print(df.values.__array_interface__)
print(df.values.strides)

{'data': (2500822178672, False), 'strides': None, 'descr': [('', '<i4')], 'typestr': '<i4', 'shape': (3, 3), 'version': 3}
(12, 4)


In [108]:
a = df["x"]
print(df.values.__array_interface__['data'][0])
print(a.values.__array_interface__['data'][0])

2500822178672
2500822178672


In [109]:
b = df.iloc[0:2]
c = df.loc["a":"b"]
print(b.values.__array_interface__['data'][0])
print(c.values.__array_interface__['data'][0])

2500822178672
2500822178672


In [110]:
b = df[ ['x','y'] ]
c = df.iloc[ [0, 2] ]
d = df[ df > 10 ]
print(b.values.__array_interface__['data'][0])
print(c.values.__array_interface__['data'][0])
print(d.values.__array_interface__['data'][0])

2500824807072
2500795394080
2500818930864


In [111]:
print(df._is_view)
print(b._is_view)
print(c._is_view)
print(d._is_view)

True
True
True
True


In [116]:
data = [
    ["가", 0, 1 ],
    ["나", 2, 3 ],
    ["다", 4, 5 ],
]
df = DataFrame(data, index=['a', "b", "c"], columns=['x', 'y', 'z'])
df

x  y  z
a  가  0  1
b  나  2  3
c  다  4  5

In [117]:
print(df["x"]._is_view)
print(df.iloc[0]._is_view)
print(df.iloc[0:2]._is_view)
print(df.iloc[[0, 2]]._is_view)

True
False
False
False


## 6.4 판다스의 BlockManager

In [168]:
from pandas import DataFrame 

data = [
    [0, 1, 2.0],
    [3, 4, 5.0],
    [6, 7, 8.0],
]
df = DataFrame(data, index=["a", "b", "c"], columns=["x", "y", "z"])
df._data

BlockManager
Items: Index(['x', 'y', 'z'], dtype='object')
Axis 1: Index(['a', 'b', 'c'], dtype='object')
FloatBlock: slice(2, 3, 1), 1 x 3, dtype: float64
IntBlock: slice(0, 2, 1), 2 x 3, dtype: int64

In [169]:
print(df['x'].values.strides)
print(df['x'].values.__array_interface__['data'][0])
print(df['y'].values.__array_interface__['data'][0])
print(df['z'].values.__array_interface__['data'][0])

(8,)
2500797131408
2500797131432
2500827232128


In [170]:
print(df.iloc[0]._is_view)
print(df['x']._is_view)
print(df.iloc[:, 2]._is_view)

False
True
True


In [171]:
df['w'] = 10
print(df._data)

BlockManager
Items: Index(['x', 'y', 'z', 'w'], dtype='object')
Axis 1: Index(['a', 'b', 'c'], dtype='object')
FloatBlock: slice(2, 3, 1), 1 x 3, dtype: float64
IntBlock: slice(0, 2, 1), 2 x 3, dtype: int64
IntBlock: slice(3, 4, 1), 1 x 3, dtype: int64


In [172]:
print(df.values)
print(df._data)

[[ 0.  1.  2. 10.]
 [ 3.  4.  5. 10.]
 [ 6.  7.  8. 10.]]
BlockManager
Items: Index(['x', 'y', 'z', 'w'], dtype='object')
Axis 1: Index(['a', 'b', 'c'], dtype='object')
FloatBlock: slice(2, 3, 1), 1 x 3, dtype: float64
IntBlock: [0 1 3], 3 x 3, dtype: int64


In [173]:
print(df.values[:,0].__array_interface__['data'][0])
print(df['x'].values.__array_interface__['data'][0])

2500797065536
2500818924384


## 6.5 getter와 setter 메서드

In [189]:
import numpy as np
from pandas import DataFrame

a = np.array( [ 10, 20, 30 ] )
cond = a >= 20
b = a[cond]
b[0] = 100
print(a)

[10 20 30]


In [12]:
cond = a >= 20
a[cond] = 0
print(a)

[10  0  0]


In [13]:
class MyIndexing:
    def __init__(self):
        self.data = [10, 11, 12, 13]
       
    def __getitem__(self, idx):
        return self.data[idx]
   
    def __setitem__(self, idx, val):
        self.data[idx] = val

In [14]:
객체 = MyIndexing()
print(객체[3])

13


In [15]:
객체[3] = 20

In [190]:
cond = a >= 20
# a[cond] = 0
a.__setitem__(cond, 0)
print(a)

[10  0  0]


## 6.6.	SettingWithCopyWarning

In [175]:
from pandas import DataFrame

In [244]:
data = [
    [0, 1, 2],
    [3, 4, 5],    
    [6, 7, 8]
]

df = DataFrame(data, index=["a", "b", "c"], columns=["x", "y", "z"])
df

x  y  z
a  0  1  2
b  3  4  5
c  6  7  8

In [245]:
t = df.iloc[0:2]
t['w'] = 10
print(df)

   x  y  z
a  0  1  2
b  3  4  5
c  6  7  8


<ipython-input-245-eb552d4a339f>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['w'] = 10


In [246]:
df.iloc[ [0, 1] ]['w'] = 10
print(df)

   x  y  z
a  0  1  2
b  3  4  5
c  6  7  8


<ipython-input-246-48a947db811c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[ [0, 1] ]['w'] = 10


In [247]:
df.iloc[ 0:2 ]['w'] = 10
print(df)

   x  y  z
a  0  1  2
b  3  4  5
c  6  7  8


<ipython-input-247-43e8770ee873>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[ 0:2 ]['w'] = 10


In [248]:
df.loc[:, 'w'] = 10
print(df)

   x  y  z   w
a  0  1  2  10
b  3  4  5  10
c  6  7  8  10


In [249]:
df.loc["a":"b", 'v'] = 20
df

x  y  z   w     v
a  0  1  2  10  20.0
b  3  4  5  10  20.0
c  6  7  8  10   NaN

In [250]:
# df[df['x'] > 3]['y'] = 20
df.loc[df['x'] > 3, 'y'] = 20
df

x   y  z   w     v
a  0   1  2  10  20.0
b  3   4  5  10  20.0
c  6  20  8  10   NaN